"""create_knowledge_tables

Revision ID: 37c50a7f838d
Revises: abba352ab354
Create Date: 2026-10-09 16:33:37.130136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.models.knowledge import TSVectorType


# revision identifiers, used by Alembic.
revision: str = '37c50a7f838d'
down_revision: Union[str, None] = 'abba352ab354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('episode_slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('guest', sa.String(length=255), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('video_id', sa.String(length=50), nullable=True),
    sa.Column('publish_date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('source_repo', sa.String(length=255), nullable=False),
    sa.Column('source_file_path', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_episode_slug'), 'transcripts', ['episode_slug'], unique=True)
    op.create_index(op.f('ix_transcripts_guest'), 'transcripts', ['guest'], unique=False)
    op.create_index(op.f('ix_transcripts_title'), 'transcripts', ['title'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('start_timestamp', sa.String(length=50), nullable=True),
    sa.Column('end_timestamp', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('tsv', TSVectorType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'chunk_index', name='uq_transcript_chunk_index')
    )
    op.create_index('ix_transcript_chunks_speaker', 'transcript_chunks', ['speaker'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_transcript_id'), 'transcript_chunks', ['transcript_id'], unique=False)
    op.create_index('ix_transcript_chunks_tsv', 'transcript_chunks', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_chunks_tsv', table_name='transcript_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_transcript_chunks_transcript_id'), table_name='transcript_chunks')
    op.drop_index('ix_transcript_chunks_speaker', table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index(op.f('ix_transcripts_title'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_guest'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_episode_slug'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
